version: 2.1

orbs:
  node: circleci/node@5.0.2  

jobs:
  checkoutEtTests:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Installer les dépendances du backend
          command: cd 3w5-h25-L01-backend && npm install
      - run:
          name: Exécuter les tests
          command: cd 3w5-h25-L01-backend && npm test

  integrationFrontend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Cloner le backend et le frontend
          command: |
            git clone https://github.com/guyetab/backend.git backend
            git clone https://github.com/guyetab/frontend.git frontend
      - run:
          name: Installer les dépendances du frontend
          command: cd frontend/3w5-h25-L01-frontend && npm install
      - run:
          name: Compiler le frontend
          command: cd frontend/3w5-h25-L01-frontend && npm run build
      - run:
          name: Créer le dossier public dans le backend
          command: mkdir -p backend/3w5-h25-L01-backend/public
      - run:
          name: Copier le build du frontend dans le backend
          command: cp -r frontend/3w5-h25-L01-frontend/build/* backend/3w5-h25-L01-backend/public/
      - run:
          name: Vérifier la présence des fichiers
          command: ls -Rl backend/3w5-h25-L01-backend/public
      - persist_to_workspace:
          root: backend/3w5-h25-L01-backend
          paths:
            - public

  deploiement:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: backend/3w5-h25-L01-backend
      - run:
          name: Vérification des fichiers backend/public
          command: ls -Rl backend/3w5-h25-L01-backend/public
