version: 2.1

orbs:
  node: circleci/node@5.0.2  # Utilisation de l’orb de Node.js

jobs:
  checkoutEtTests:
    docker:
      - image: circleci/node:16  # Utilisation d’une image Node.js
    steps:
      - checkout  # Clone le dépôt backend
      - run:
          name: Installer les dépendances
          command: npm install
      - run:
          name: Exécuter les tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  integrationFrontend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Cloner les dépôts backend et frontend
          command: |
            git clone https://github.com/ton-utilisateur/backend.git backend
            git clone https://github.com/ton-utilisateur/frontend.git frontend
      - run:
          name: Installer les dépendances du frontend
          command: cd frontend && npm install
      - run:
          name: Compiler le frontend
          command: cd frontend && npm run build
      - run:
          name: Copier le build dans le backend
          command: |
            mkdir -p backend/public
            cp -r frontend/build/* backend/public/
      - persist_to_workspace:
          root: backend
          paths:
            - public

  deploiement:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Vérification du dossier backend/public
          command: ls -Rl backend/public

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
